# Generated by Django 5.1.3 on 2024-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='study_level',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bakalavr'), ('Master', 'Magistr'), ('PhD', 'PhD')], max_length=50),
        ),
    ]
