# Generated by Django 5.1.3 on 2024-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_testscore_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='is_studying',
            field=models.CharField(blank=True, choices=[('Yes', 'Ha'), ('No', "Yo'q")], max_length=3),
        ),
    ]
