# Generated by Django 5.1.3 on 2024-12-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_testscore_current_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='achievements',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='citizenship',
            field=models.CharField(default='Uzbekistan', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='current_study',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
